name: Gradle Microservice

on:
  workflow_call:
    inputs:
      docker_repository_path:
        required: true
        type: string
    secrets:
      docker_registry:
        required: true
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: smartidobox/github-actions/.github/actions/setup-gradle-microservice-commons@main
      - name: Build
        run: ./gradlew build -x test -x check --no-daemon --build-cache

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: smartidobox/github-actions/.github/actions/setup-gradle-microservice-commons@main
      - name: Test
        run: ./gradlew test --no-daemon --build-cache

  code-quality:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: smartidobox/github-actions/.github/actions/setup-gradle-microservice-commons@main
      - name: Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --build-cache

  publish:
    runs-on: ubuntu-latest
    needs: [build, test, code-quality]
    steps:
      - uses: smartidobox/github-actions/.github/actions/setup-gradle-microservice-commons@main

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 22.0.0.2.java17

      - name: Install Native Image
        run: gu install native-image

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.docker_registry }}
          username: ${{ secrets.docker_registry_username }}
          password: ${{ secrets.docker_registry_password }}

      - name: Build And Push Docker Image
        env:
          DOCKER_IMAGE: ${{ format('{0}/{1}', secrets.docker_registry, inputs.docker_repository_path) }}
        run: ./gradlew dockerPushNative --no-daemon --build-cache